config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'loans#index'

  devise_for :admins
  devise_for :users

  scope :admin do
    get 'dashboard', to: 'dashboard#index'
    get ':loan_id/approve', to: 'dashboard#approve_loan', as: :admin_approve_loan
    post ':loan_id/change-status', to: 'dashboard#change_loan_status', as: :admin_request_loan
  end

  scope :users do
    resources :loans, only: %i[index new create] do
      post '/change', to: 'loans#change_loan', as: :change
      member do
        post 'repay'
      end
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :loans

  def subtract_amount(amount)
    update(wallet_balance: wallet_balance - amount)
  end

  def add_amount(amount)
    update(wallet_balance: wallet_balance + amount)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :admin

  validates :reason, presence: true
  validates :interest_rate, numericality: { greater_than: 0 }
  validates :amount, numericality: { greater_than: 0 }

  enum status: %i[requested approved open closed rejected]

  def calculate_interest_and_update
    time_elapsed = (Time.now - calculated_at) / 1.minute
    interest = amount * interest_rate * time_elapsed / (100.0 * 60.0)

    # Update loan amount with interest
    update(total_amount: amount + interest, calculated_at: Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :loans

  def add_amount(amount)
    update(wallet_balance: wallet_balance + amount)
  end

  def remove_amount(amount)
    update(wallet_balance: wallet_balance - amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    if resource.class.to_s == 'User'
      root_path
    elsif resource.class.to_s == 'Admin'
      dashboard_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_admin!
  before_action :authorize_admin
  before_action :set_loan, only: %i[approve_loan change_loan_status]

  def index
    @admin = current_admin
    @wallet_balance = @admin.wallet_balance
    params[:filter] ||= 'requested'
    @loans = case params[:filter]
             when 'approved'
               Loan.approved.includes(:user)
             when 'rejected'
               Loan.rejected.includes(:user)
             when 'open'
               Loan.open.includes(:user)
             when 'closed'
               Loan.closed.includes(:user)
             else
               Loan.requested.includes(:user)
             end
  end

  def approve_loan; end

  def change_loan_status
    case params[:status]
    when 'approved'
      handle_loan_approval
    when 'rejected'
      handle_loan_rejection
    else
      redirect_to_dashboard_with_alert('Invalid status')
    end
  end

  private

  def set_loan
    @loan = Loan.find_by(id: params[:loan_id])
    redirect_to_dashboard_with_alert('Loan not found') unless @loan
  end

  def handle_loan_approval
    if current_admin.wallet_balance < @loan.amount
      return redirect_to_dashboard_with_alert('You do not have enough amount to proceed with this loan')
    end

    if @loan.update(interest_rate: params[:interest_rate], status: :approved)
      redirect_to_dashboard_with_alert('Loan approved successfully!')
    else
      redirect_to_approval_page_with_alert(@loan)
    end
  end

  def handle_loan_rejection
    if @loan.update(status: :rejected)
      redirect_to_dashboard_with_alert('Loan rejected successfully!')
    else
      redirect_to_dashboard_with_alert(@loan.errors.full_messages.join(','))
    end
  end

  def redirect_to_dashboard_with_alert(alert_message)
    redirect_to dashboard_path, alert: alert_message
  end

  def redirect_to_approval_page_with_alert(loan)
    redirect_to admin_approve_loan_path(loan), alert: loan.errors.full_messages.join(',')
  end

  def authorize_admin
    redirect_to root_path unless current_admin
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan, only: [:change_loan]

  def index
    @wallet_balance = current_user.wallet_balance
    @pagy, @loans = pagy(current_user.loans, items: 10)
  end

  def new
    @loan = Loan.new
  end

  def create
    @loan = current_user.loans.build(loan_params.merge(admin_id: Admin.first.id))

    if @loan.save
      redirect_to loans_path, notice: 'Loan requested successfully.'
    else
      flash[:alert] = @loan.errors.full_messages.join(', ')
      render :new
    end
  end

  def change_loan
    case params[:status]
    when 'open'
      open_loan
    when 'rejected'
      reject_loan
    else
      redirect_to loans_path, alert: 'Invalid loan status!'
    end
  end

  def repay
    @loan = current_user.loans.find_by(id: params[:id])
    amount_to_repay = @loan.total_amount
    if current_user.wallet_balance >= amount_to_repay
      ActiveRecord::Base.transaction do
        current_user.remove_amount(amount_to_repay)
        Admin.first.add_amount(amount_to_repay)
        @loan.update(status: :closed)
      end
      redirect_to loans_path, notice: 'Loan repaid successfully.'
    else
      redirect_to loans_path, alert: 'Loan can not be paid because your wallet has insufficent amount!'
    end
  end

  private

  def set_loan
    @loan = current_user.loans.find_by(id: params[:loan_id])
    redirect_to loans_path, alert: 'Loan not exist!' unless @loan
  end

  def loan_params
    params.require(:loan).permit(:reason, :status, :amount, :interest_rate)
  end

  def open_loan
    ActiveRecord::Base.transaction do
      Admin.first.subtract_amount(@loan.amount)
      current_user.add_amount(@loan.amount)
      @loan.update(status: :open, total_amount: @loan.amount, calculated_at: Time.now)
    end
    redirect_to loans_path, notice: 'Loan credited to your wallet!'
  end

  def reject_loan
    @loan.update(status: :rejected)
    redirect_to loans_path, notice: 'Loan rejected successfully!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def filter_class(status)
    params[:filter] == status ? 'text-blue-500 font-bold mr-2' : 'mr-2'
  end
end

app/views/admins/shared/_error_messages.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-md">
    <% if resource.errors.any? %>
      <div id="error_explanation" data-turbo-cache="false">
        <h2 class="text-red-600">
          <%= I18n.t("errors.messages.not_saved",
                     count: resource.errors.count,
                     resource: resource.class.model_name.human.downcase)
           %>
        </h2>
        <ul class="list-disc pl-5 text-red-600">
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<div class="flex justify-center">
  <div class="w-full max-w-md">
    <%= link_to "Log in as user", new_user_session_path %><br />

    <% if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end %>

    <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end %>

    <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
      <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
    <% end %>

    <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
      <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
    <% end %>

    <% if devise_mapping.omniauthable? %>
      <% resource_class.omniauth_providers.each do |provider| %>
        <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
      <% end %>
    <% end %>
  </div>
</div>

app/views/dashboard/approve_loan.html.erb
<div class="container mx-auto flex flex-col justify-center h-screen">
  <div class="w-full max-w-md mx-auto">
    <h1 class="text-2xl font-bold mb-4">Approve Loan</h1>

    <%= form_tag(admin_request_loan_path(@loan), method: :post, class: "loan-approval-form") do %>
      <div class="mb-4">
        <%= label_tag "interest_rate", "Interest Rate:", class: "block text-sm font-medium text-gray-700" %>
        <%= text_field_tag "interest_rate", @loan.interest_rate, class: "form-input mt-1 block w-full rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" %>
      </div>
      <%= hidden_field_tag :status, 'approved' %>
      <%= submit_tag 'Approve', class: 'px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:bg-blue-600' %>
      <%= link_to 'Back', dashboard_path, class: 'px-4 py-2 bg-yello-500 text-white rounded-md hover:bg-yellow-600 focus:outline-none focus:bg-blue-600' %>
    <% end %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container mx-auto">
  <h1 class="text-2xl font-bold mb-4">Welcome <%= @admin.name %> to Dashboard</h1>

  <!-- Filter options -->
  <div class="mb-4">
    <label class="font-bold mr-2">Filter:</label>
    <%= link_to "Requested", dashboard_path(filter: 'requested'), class: filter_class('requested') %>
    <%= link_to "Approved", dashboard_path(filter: 'approved'), class: filter_class('approved') %>
    <%= link_to "Rejected", dashboard_path(filter: 'rejected'), class: filter_class('rejected') %>
    <%= link_to "Open", dashboard_path(filter: 'open'), class: filter_class('open') %>
    <%= link_to "Closed", dashboard_path(filter: 'closed'), class: filter_class('closed') %>
  </div>

  <!-- Tabular view for loan requests based on the selected filter -->
  <div class="mb-8">
    <h3 class="text-lg font-bold mb-4">Loans:</h3>
    <% if @loans.empty? %>
      <p class="text-gray-500">There are no loans at the moment.</p>
    <% else %>
      <table class="min-w-full divide-y divide-gray-200">
        <thead>
          <tr>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">User</th>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Amount</th>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Interest Rate</th>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Status</th>
            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">Action</th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <% @loans.each do |loan| %>
            <tr>
              <td class="px-6 py-4 whitespace-no-wrap"><%= loan.user.name %></td>
              <td class="px-6 py-4 whitespace-no-wrap"><%= loan.amount %> ₹</td>
              <td class="px-6 py-4 whitespace-no-wrap"><%= loan.interest_rate %>%</td>
              <td class="px-6 py-4 whitespace-no-wrap"><%= loan.status.capitalize %></td>
              <td class="px-6 py-4 whitespace-no-wrap flex items-center">
                <% if loan.status == 'requested' %>
                  <%= link_to 'Approve', admin_approve_loan_path(loan), class: 'px-4 py-2 bg-green-500 text-white rounded-md hover:bg-green-600 focus:outline-none focus:bg-green-600 mr-2' %>
                  <%= button_to 'Reject', admin_request_loan_path(loan, status: 'rejected'), method: :post, class: 'px-4 py-2 bg-red-500 text-white rounded-md hover:bg-red-600 focus:outline-none focus:bg-red-600', data: { turbo_confirm: 'Are you sure you want to reject this loan request?' } %>
                <% else %>
                  -
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="bg-blue-500 text-white py-4">
  <div class="container mx-auto px-4 flex justify-between items-center">
      <h1 class="text-2xl font-semibold">Loans</h1>
      <div>
          <% if current_admin || current_user %>
            <% wallet_balance = current_user.present? ? current_user.wallet_balance : current_admin.wallet_balance %>
            <span class="text-white mr-4">Wallet Balance: <%= wallet_balance %> ₹</span>
          <% end %>
          <% if current_user %>
            <%= link_to "Request Loan", new_loan_path, class: 'text-white font-semibold bg-green-500 px-4 py-2 rounded hover:bg-green-600 transition-colors' %>
          <% end %>

          <% logout_link = current_user.present? ? destroy_user_session_path : destroy_admin_session_path %>
          <% if current_admin || current_user %>
            <%= link_to "Logout", logout_link, class: 'text-white font-semibold bg-red-600 px-4 py-2 rounded hover:bg-red-700 transition-colors', data: { turbo_method: 'delete' } %>
          <% end %>
      </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanManagementSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if notice.present? %>
      <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert" data-controller='flash-message'>
        <span class="block sm:inline"><%= notice %></span>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert" data-controller='flash-message'>
        <span class="block sm:inline"><%= alert %></span>
      </div>
    <% end %>
    
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/loans/index.html.erb
<main class="container mx-auto px-4 py-8">
  <!-- User Loans Section -->
  <section class="mb-8">
    <h2 class="text-lg font-semibold mb-4">User Loans</h2>
    <%== pagy_nav(@pagy) %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-2">
        <!-- Sample Loan Card -->
        <% if @loans.exists? %>
          <% @loans.each do |loan| %>
            <div class="bg-white shadow-md rounded-md p-4">
                <h3 class="text-lg font-semibold mb-2">Loan <%= loan.id %></h3>
                <p class="text-gray-500 mb-2">Reason: <%= loan.reason %></p>
                <p class="text-gray-500 mb-2">Status: <%= loan.status.capitalize %></p>
                <p class="text-gray-500 mb-2">Amount: <%= loan.amount %>₹</p>
                <p class="text-gray-500 mb-2">Interset Rate: <%= loan.interest_rate %>%</p>
                <% if loan.status.downcase == 'open' %>
                  <p class="text-gray-500 mb-2">Total Amount to be Repaid: <%= loan.total_amount %>₹</p>
                  <div class="flex justify-between">
                    <%= button_to 'Repay', repay_loan_path(loan), method: :post, class: 'bg-green-500 text-white px-4 py-2 rounded-md', data: { turbo_confirm: 'Are you sure you want to pay this loan?' } %>
                  </div>
                <% end %>
                <% if loan.status.downcase == 'approved' %>
                  <div class="flex justify-between">
                    <%= button_to 'Confirm', loan_change_path(loan, status: 'open'), method: :post, class: 'bg-green-500 text-white px-4 py-2 rounded-md', data: { turbo_confirm: 'Are you sure you want to peoceed this loan request?' } %>
                    <%= button_to 'Reject', loan_change_path(loan, status: 'rejected'), method: :post, class: 'bg-red-500 text-white px-4 py-2 rounded-md', data: { turbo_confirm: 'Are you sure you want to reject this loan?' } %>
                  </div>
                <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="col-span-3">
            <div class="bg-white shadow-md rounded-md p-4">
              <h3 class="text-lg font-semibold mb-2">No loans</h3>
              <p class="text-gray-500 mb-2">There are currently no loans to display.</p>
            </div>
          </div>
        <% end %>
    </div>
  </section>
</main>

app/views/loans/new.html.erb
<div class="container mx-auto px-4 py-8">
  <h1 class="text-2xl font-semibold mb-4">New Loan</h1>
  
  <%= form_with(model: @loan, method: "post", class: "max-w-md", data: { turbo: false }) do |form| %>
    <div class="mb-4">
      <%= form.label :reason, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.text_area :reason, class: "form-input w-full rounded-md border-gray-300 shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.label :amount, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.number_field :amount, class: "form-input w-full rounded-md border-gray-300 shadow-sm" %>
    </div>

    <div class="mb-4">
      <%= form.label :interest_rate, class: "block text-gray-700 font-bold mb-2" %>
      <%= form.number_field :interest_rate, class: "form-input w-full rounded-md border-gray-300 shadow-sm", disabled: true %>
      <p class="text-gray-500 text-sm">Note: Interest rate can be changed by admin.</p>
    </div>

    <div class="mb-4">
      <%= form.submit "Create Loan", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <%= link_to "Back", loans_path, class: "bg-yellow-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" data-turbo-cache="false">
    <h2 class="text-sm font-semibold mb-2">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="mb-1"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "text-blue-500 hover:text-blue-700 underline" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "text-blue-500 hover:text-blue-700 underline" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "text-blue-500 hover:text-blue-700 underline" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "text-blue-500 hover:text-blue-700 underline" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "text-blue-500 hover:text-blue-700 underline" %><br />
<% end %>

<%= link_to "Log in as admin", new_admin_session_path, class: "text-blue-500 hover:text-blue-700 underline" %><br />